---
app_name: devops-app
app_container_name: "{{ app_name }}"
app_port: 5000
app_restart_policy: unless-stopped
app_healthcheck_path: /health

# Expected to come from vault/group vars
# dockerhub_username:
# dockerhub_password:
# docker_image_tag: latest

docker_image_tag: latest
docker_image: "{{ dockerhub_username }}/{{ app_name }}"
app_env: {}
