---
docker_apt_arch: "amd64"
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_users:
  - "{{ ansible_user | default('ubuntu') }}"

