{{- if and .Values.rollout.enabled .Values.rollout.analysis.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "devops-info-service.analysisTemplateName" . }}
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  metrics:
    - name: health-webcheck
      interval: {{ .Values.rollout.analysis.interval | quote }}
      count: {{ .Values.rollout.analysis.count }}
      failureLimit: {{ .Values.rollout.analysis.failureLimit }}
      successCondition: {{ .Values.rollout.analysis.successCondition | quote }}
      provider:
        web:
          url: {{ printf "http://%s.%s.svc:%v/health" (include "devops-info-service.fullname" .) .Release.Namespace .Values.service.port | quote }}
          jsonPath: "{$.status}"
{{- end }}
