apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-info-service.configFileName" . }}
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  config.json: |-
{{ .Files.Get "files/config.json" | indent 4 }}
