apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-info-service.fullname" . }}-app-secrets
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  username: {{ .Values.secrets.username | quote }}
  password: {{ .Values.secrets.password | quote }}
  api_key: {{ .Values.secrets.apiKey | quote }}
