apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-info-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dart-NEW/DevOps-Core-Course.git
    targetRevision: lab12
    path: k8s/devops-info-service
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: service.nodePort
          value: "30083"
  destination:
    server: https://kubernetes.default.svc
    namespace: lab13
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
